# Site settings
title: Seren Davies
email: hello@serendavies.me
description: > # this means to ignore newlines until "baseurl:"
    The ramblings of a girly geek
baseurl: ""
url: "http://www.serendavies.me" # the base hostname & protocol for your site
twitter_username: ninjanails
github_username:  ninjanails

# Build settings
markdown: kramdown
